### ISSUE TITLE
Can't add a map

### ISSUE THREAD

**Issue by WhereAreDoggo** [debate-map/app#342]
(Browser: Chrome)
Whenever I try to add a map, it gives me this error:

Unknown type "AddDMapInput"
Unknown type "AddDMapInput"
Unknown field "addDMap" on type "MutationRoot". Did you mean "addMap"?

ApolloError
    at new ApolloError (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:157349)
    at https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:128851
    at both (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:284567)
    at https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:284431
    at new Promise (<anonymous>)
    at Object.then (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:284386)
    at Object.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:284608)
    at notifySubscription (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:34487)
    at onNotify (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:35191)
    at _proto2.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:36032)
    at https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:285554
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:285514)
    at Object.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:280399)
    at notifySubscription (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:34487)
    at onNotify (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:35191)
    at _proto2.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:36032)
    at Object.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:165746)
    at notifySubscription (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:34487)
    at onNotify (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:35191)
    at _proto2.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:36032)
    at notifySubscription (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:34487)
    at onNotify (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:35191)
    at _proto2.next (https://debatemap.app/app.2db4303a28d6cc2d61f5.js:382:36032)
    at https://debatemap.app/app.2db4303a28d6cc2d61f5.js:177:184309

**Comment by Venryx** [comment]
Yeah sorry about that (and thanks for the quick bug report!).

I actually noticed the error in Sentry a few minutes ago, and have uploaded the fix already. (made a recent class rename, and forgot to sync the graphql request name with backend endpoint name)

**Comment by Venryx** [comment]
@WhereAreDoggo Btw, I noticed in Sentry that you also hit an error when trying to add a child node. xd

It seems to be a bug in the permission checks, when the map/node access-policy is set to "Private (owner only)". I will try to fix that in the next few days, but for now, you should be able to get past the error by changing the map's two access-policies to "Public, ungoverned (standard)" rather than private.
